# Generated by Django 6.1 on 2026-08-21 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(db_index=True, max_length=4096, unique=True)),
                ('status', models.CharField(choices=[('optional', 'Optional'), ('selected', 'Selected'), ('rejected', 'Rejected')], db_index=True, default='optional', max_length=16)),
                ('provenance', models.CharField(blank=True, db_index=True, max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_mtime', models.FloatField()),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('phash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('captured_at_source', models.CharField(choices=[('exif', 'EXIF'), ('filename', 'Filename'), ('file_mtime', 'File mtime')], max_length=16)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=8)),
                ('live_photo_video_path', models.CharField(blank=True, max_length=4096, null=True)),
                ('missing', models.BooleanField(default=False)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['captured_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicatePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hamming_distance', models.PositiveSmallIntegerField()),
                ('resolved', models.BooleanField(default=False)),
                ('photo_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_pairs_as_a', to='core.photo')),
                ('photo_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_pairs_as_b', to='core.photo')),
            ],
        ),
    ]
