# Generated by Django 6.1 on 2026-08-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_photo_account_photo_remote_id_photo_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='remote_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
