# Generated by Django 6.1 on 2026-08-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='account',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='photo',
            name='remote_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='source',
            field=models.CharField(choices=[('local', 'Local'), ('icloud', 'iCloud')], db_index=True, default='local', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_id__isnull', False)), fields=('account', 'remote_id'), name='unique_account_remote_id_when_present'),
        ),
    ]
