# Generated by Django 6.1 on 2026-08-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_photo_remote_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='original_path',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
    ]
