# Generated by Django 6.1 on 2026-08-24 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_photo_original_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('local', 'Local'), ('icloud', 'iCloud')], max_length=8)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('path', models.CharField(blank=True, default='', max_length=4096)),
                ('account', models.CharField(blank=True, default='', max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='source_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='core.source'),
        ),
    ]
